-- Import Hardware Data from Excel
INSERT INTO public.hardware_master (hardware_type, sku_no, type, product_name, description, price_gbp, minimum_quantity, required_optional, tags, comments) VALUES
('Server', 'TTX-AI-GW-001', 'TTX-Vision', 'Ai Vision Server (AE Gen 2)', 'CPU Model: Intel(R) Core(TM) i5-12500 LGA 1700 Socket Processor, GPU: NVIDIA RTX 5070 12 GB, SSD: 1*M.2 256GB PCIe Gen4x 4, NVMe, RAM: 2* 32GB DDR5 4000MHz', 2100, 1, 'Required', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'This is calculated based on the number of cameras on site *Note: 1 server per 5 Camera*'),
('Server', 'TTX-AI-GW-002', 'TTX-Vision', 'Vision Training Server (AE Gen 2)', 'CPU Model: Intel(R) Core(TM) i5-12500 LGA 1700 Socket Processor, GPU: NVIDIA RTX 5070 12 GB, SSD: 1*M.2 256GB PCIe Gen4x 4, NVMe, RAM: 2* 32GB DDR5 4000MHz', 2100, 0, 'Optional', 'ONP-VSN, ONP-VSN-CORE', 'On-Prem - One per site is required at minimum'),
('Camera', 'TTX-AI-CAM-011', 'TTX-Vision', 'MER3-506-58G3COL-P-4MM', 'Colour Camera 4mm', 600, 1, 'Required', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'One per site is required at minimum'),
('Camera', 'TTX-AI-CAM-012', 'TTX-Vision', 'MER3-506-58G3COL-P-6MM', 'Colour Camera 6mm', 600, 1, NULL, NULL, NULL),
('Camera', 'TTX-AI-CAM-013', 'TTX-Vision', 'MER3-506-58G3MON-P-4MM', 'Mono Camera 4mm', 600, 1, NULL, NULL, NULL),
('Camera', 'TTX-AI-CAM-014', 'TTX-Vision', 'MER3-506-58G3MON-P-6MM', 'Mono Camera 6mm', 600, 1, NULL, NULL, NULL),
('Light', 'TTX-AI-LIGHT-021', 'TTX-Vision', 'TBC', 'TBC', 400, 1, 'Required', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'One per site is required at minimum'),
('PLC', 'TTX-AI-PLC-031', 'TTX-Vision', 'Arduino Opta RS485', 'This plc has 4 outputs', 180, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('PLC Expansion', 'TTX-AI-PLC-032', 'TTX-Vision', 'Arduino Opta Extention SSR', 'This is an addon to the PLC with 8 SSR Outputs', 150, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('Storage', 'TTX-AI-IOT-NAS-041', 'TTX-Vision', 'NAS 2-4 Bay with RAID', 'On site storage with raid configured to switch the bay in case of hdd/ssd failure', 775, 1, 'Required', 'ONP-VSN, ONP-VSN-CORE', 'One per site is required at minimum - small medium and large'),
('VPN', 'TTX-AI-IOT-VPN-046', 'TTX-Vision', 'EWON COSY', 'For Site-to-Site or for standard Remote access', 650, 1, 'Required', 'ONP-VSN, HYB-VSN, ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'One per site is required at minimum'),
('VPN', 'TTX-IOT-VPN-047', 'TTX-IOT', 'EWON COSY + 4G', 'For Site-to-Site or for standard Remote access where internet is not provide our 4G sim can go in', 650, 1, 'Optional', 'ONP-CORE, HYB-CORE', 'One per site is required at minimum'),
('TV Device', 'TTX-IOT-AI-TV-051', 'TTX-Vision', 'TV Device - Dell Optiplex 3060/3050', 'For Tv device mode to load portal page with list view and efficiency page', 250, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('TV Device', 'TTX-IOT-AI-Android-052', 'TTX-Vision', 'TV Device Android with MDM', 'For Tv device mode or kiosk mode including mdm license per device', 300, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('HMI', 'TTX-AI-HMI-056', 'TTX-Vision', 'HMI - Weintek cMT3072X (7" touch)', 'For communicating with plc and other things', 400, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('10G SFP ADDON', 'TTX-AI-GW-003', 'TTX-Vision', '10G SFP ADDON', 'This is for the SFP port on the ai server', 200, 0, 'Optional', 'ONP-VSN, HYB-VSN, ONP-VSN-CORE, HYB-VSN-CORE', 'As required by Customer'),
('Processing Server', 'TTX-PRT-IOT-GW-061', 'TTX-Portal', 'Processing Server - Line efficiency', 'CPU Model: Intel(R) Core(TM) i7-14700, SSD: 1 TB, RAM: 32GB', 1000, 2, 'Required', 'ONP-VSN, HYB-VSN, ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'Two per site is required at'),
('Load Balancer', 'TTX-PRT-GW-062', 'TTX-Portal', 'Hardware load Balancer', 'Hardware load balancer for on-premise deployments', 1350, 1, 'Required', 'ONP-VSN, ONP-CORE, ONP-VSN-CORE', 'One per site is required at minimum'),
('Gateway', 'TTX-IOT-GW-071', 'TTX-IOT', 'IoT Gateway server', 'CPU Model: Intel(R) Core(TM) i5-12700, SSD: 256 GB, RAM: 16GB', 700, 2, 'Required', 'ONP-CORE, HYB-CORE', 'One per site is required at minimum'),
('IoT Device', 'TTX-IOT-076', 'TTX-IOT', 'IoT Device 868mhz', 'EU and UK', NULL, 1, 'Required', 'ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'One per site is required at minimum'),
('IoT Receiver', 'TTX-IOT-077', 'TTX-IOT', 'IoT Receiver 868 mhz', 'EU and UK', NULL, 1, 'Required', 'ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', 'One per 10 device per site'),
('CTs', 'TTX-IOT-078', 'TTX-IOT', 'Energy CT''s 200amp', 'all, not specific to region', NULL, 3, 'Optional', 'ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', '3 per device required at minimum'),
('CTs', 'TTX-IOT-079', 'TTX-IOT', 'Energy CT''s 600amp', 'all, not specific to region', NULL, 3, 'Optional', 'ONP-CORE, HYB-CORE, ONP-VSN-CORE, HYB-VSN-CORE', '3 per device required at minimum'),
('Cloud', 'TTX-PRT-Cloud-086', 'TTX-Portal', 'Cloud Compute', 'EC2 and ECS with Auto Scale', NULL, 1, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', 'EC2 and ECS with Auto Scale'),
('Cloud', 'TTX-PRT-Cloud-087', 'TTX-Portal', 'Cloud RDS', 'Need one duplicate RDS for HA will cost double', NULL, 2, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', 'Need one duplicate RDS for HA will cost double'),
('Cloud', 'TTX-PRT-Cloud-088', 'TTX-Portal', 'Cloud Storage', '1 with multiple AZs', NULL, 1, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', '1 with multiple AZs'),
('Cloud', 'TTX-PRT-Cloud-089', 'TTX-Portal', 'Cloud Logs', 'Auto', NULL, 1, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', 'Auto'),
('Cloud', 'TTX-PRT-Cloud-090', 'TTX-Portal', 'Cloud Load Balancer', 'Cross AZ load balancer', NULL, 1, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', 'Cross AZ load balancer'),
('Cloud', 'TTX-PRT-Cloud-091', 'TTX-Portal', 'Cloud-GPU-Server', 'On-cloud dedicated server', NULL, 1, 'Required', 'HYB-VSN, HYB-CORE, HYB-CORE-VSN', 'auto scaled')
ON CONFLICT (sku_no) DO UPDATE SET
  hardware_type = EXCLUDED.hardware_type,
  type = EXCLUDED.type,
  product_name = EXCLUDED.product_name,
  description = EXCLUDED.description,
  price_gbp = EXCLUDED.price_gbp,
  minimum_quantity = EXCLUDED.minimum_quantity,
  required_optional = EXCLUDED.required_optional,
  tags = EXCLUDED.tags,
  comments = EXCLUDED.comments,
  updated_at = now();