// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { queueMutation, extractTableFromUrl } from '@/lib/offlineQueue';

const SUPABASE_URL = "https://tjbiyyejofdpwybppxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYml5eWVqb2ZkcHd5YnBweGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDgxMTIsImV4cCI6MjA3MzAyNDExMn0.525HE5OtL-Cvvmumq6t0APuf_Wmxy2hZO1jYdG0D1BU";

// Mutation methods that should be queued when offline
const MUTATION_METHODS = ['POST', 'PATCH', 'DELETE', 'PUT'];

// Paths that must NOT be queued (auth, realtime, storage uploads)
const NEVER_QUEUE_PATHS = ['/auth/v1/', '/realtime/v1/', '/storage/v1/'];

/**
 * Offline-aware fetch wrapper.
 * - GET requests: pass through (Workbox caching handles offline reads)
 * - Mutations (POST/PATCH/DELETE/PUT) to REST API: if network fails,
 *   queue in IndexedDB and return a fake 200 so the app doesn't error.
 */
const offlineAwareFetch: typeof globalThis.fetch = async (input, init) => {
  const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : (input as Request).url;
  const method = (init?.method || 'GET').toUpperCase();
  
  const isMutation = MUTATION_METHODS.includes(method);
  const isRestApi = url.includes('/rest/v1/');
  const isRpc = url.includes('/rest/v1/rpc/');
  const shouldQueue = isMutation && isRestApi && !NEVER_QUEUE_PATHS.some(p => url.includes(p));

  try {
    const response = await globalThis.fetch(input, init);
    return response;
  } catch (error) {
    // Network error (offline)
    if (shouldQueue && !navigator.onLine) {
      // Extract headers
      const headers: Record<string, string> = {};
      if (init?.headers) {
        if (init.headers instanceof Headers) {
          init.headers.forEach((v, k) => { headers[k] = v; });
        } else if (Array.isArray(init.headers)) {
          init.headers.forEach(([k, v]) => { headers[k] = v; });
        } else {
          Object.assign(headers, init.headers);
        }
      }

      const table = extractTableFromUrl(url);
      const operationMap: Record<string, string> = { POST: 'insert', PATCH: 'update', DELETE: 'delete', PUT: 'upsert' };
      
      await queueMutation({
        id: crypto.randomUUID(),
        url,
        method,
        headers,
        body: typeof init?.body === 'string' ? init.body : null,
        timestamp: Date.now(),
        table: isRpc ? `rpc/${table}` : table,
        operation: operationMap[method] || method.toLowerCase(),
      });

      console.log(`[OfflineFetch] Queued ${method} ${table} for sync`);

      // Return a fake success response so the app doesn't show errors
      const fakeBody = method === 'DELETE' ? '' : JSON.stringify([]);
      return new Response(fakeBody, {
        status: method === 'DELETE' ? 204 : 200,
        statusText: 'OK (queued offline)',
        headers: new Headers({ 'content-type': 'application/json', 'x-offline-queued': 'true' }),
      });
    }

    // Not a queuable request — rethrow
    throw error;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: offlineAwareFetch,
  },
});
