// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjbiyyejofdpwybppxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYml5eWVqb2ZkcHd5YnBweGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDgxMTIsImV4cCI6MjA3MzAyNDExMn0.525HE5OtL-Cvvmumq6t0APuf_Wmxy2hZO1jYdG0D1BU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});